FROM n8nio/n8n

# Set environment variables
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=password
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=dpg-d07q8jqdbo4c73bpvd90-a
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=n8n_wz4s
ENV DB_POSTGRESDB_USER=n8ndb
ENV DB_POSTGRESDB_PASSWORD=aV9rzvILhjgMzCTBtTYLxA7VrQCXRqs7

# Expose the port n8n will run on
EXPOSE 5678

# Start n8n
CMD ["n8n", "start"]
