FROM n8nio/n8n

# Set environment variables
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=password
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=
ENV DB_POSTGRESDB_USER=
ENV DB_POSTGRESDB_PASSWORD=

# Expose the port n8n will run on
EXPOSE 5678

# Start n8n
CMD ["n8n", "start"]
