services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "password"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "YOUR_POSTGRES_HOST"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "YOUR_DATABASE_NAME"
      - key: DB_POSTGRESDB_USER
        value: "YOUR_DATABASE_USER"
      - key: DB_POSTGRESDB_PASSWORD
        value: "YOUR_DATABASE_PASSWORD"
    disk:
      name: persistent
      mountPath: /persistent
      sizeGb: 1

databases:
  - type: postgres
    name: n8n-db
    plan: free
    properties:
      databaseName: 
      user: 
      password: 
