services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_ENCRYPTION_KEY
        value: randomlongstringhere
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /home/node/.n8n/database.sqlite
      - key: WEBHOOK_URL
        value: https://your-n8n-service.onrender.com

disks:
  - name: n8n-data
    sizeGB: 1
